version: '3.8'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=microservice
      - POSTGRES_USER=userpostgres
      - POSTGRES_PASSWORD=qwerty1234
    image: postgres:16.2-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  app:
    container_name: calculator
    ports:
      - "8080:8080"
    build: 
      context: .
    depends_on:
          db:
            condition: service_healthy
    environment:
      - DATABASE_URL=postgres://userpostgres:qwerty1234@db:5432/microservice?sslmode=disable