version: '3.8'

services:
  calculater:
    container_name: calculater
    command: ./microservice
    ports:
      - "8000:8080"
    depends_on:
      - db
    build:
      dockerfile: dockerfile

  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=microservice
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_USER=postgres
    image: postgres:16.2-alpine
